### ISSUE TITLE
I instant leave the lobby when joining a game via sign

### ISSUE THREAD

**Issue by AlexProgrammerDE** [montlikadani/RageMode#10]
### Details
Plugin version: v1.8.3

Software: Paper Spigot version: git-Paper-333 (1.15.2)

Relevant plugins:

### Console error
```
No errors. Just:
[22:23:25 INFO]: You whisper to Pistonmaster: We wish you a good game!
```

### Configuration file(s)

config.yml: https://pastebin.com/btAWysGQ
I will provide more config files if needed.

**Comment by AlexProgrammerDE** [comment]
Ok manually koining seems to work. I only get this issue with signs.

**Comment by AlexProgrammerDE** [comment]
I think i resolved it. Reloading the plugin caused this weird behaviour.

**Comment by AlexProgrammerDE** [comment]
nope still occured. Really weird...

**Comment by montlikadani** [comment]
So this is only occurs when you joins from signs?

**Comment by AlexProgrammerDE** [comment]
@montlikadani yes.And i have no sign plugin i think.

**Comment by AlexProgrammerDE** [comment]
@montlikadani I recorded it: https://streamable.com/gog5s4

**Comment by AlexProgrammerDE** [comment]
I didnt get any error. Is there a way to debug whats happening on the server?

**Comment by AlexProgrammerDE** [comment]
[threads.txt](https://github.com/montlikadani/RageMode/files/4739739/threads.txt)
Ok i made a debug log with that issue. Hope it helps resolving this.

**Comment by AlexProgrammerDE** [comment]
@montlikadani ah i found it! The lobby item manager detects the right click of the sign also as a click of the item in the specific slot after teleporting. I clicked with the slot that will contain the back to lobby item. Can you fix that?

**Comment by montlikadani** [comment]
This already been fixed in the latest versions and should works. [L489-L504](https://github.com/montlikadani/RageMode/blob/master/src/main/java/hu/montlikadani/ragemode/gameUtils/GameUtils.java#L489-L504)

**Comment by AlexProgrammerDE** [comment]
@montlikadani is the fix already released?

**Comment by AlexProgrammerDE** [comment]
@montlikadani ok it seems like it doesnt work.

**Comment by AlexProgrammerDE** [comment]
@montlikadani any idea why this is still happening? Im using the newest version. I think cancelling the right click event before teleporting would fix it completely. I mean adding:
`event.setCancelled(true);`
in this line would fix it: https://github.com/montlikadani/RageMode/blob/3d6912f340f0c96b0b76b936bc5fd2c68b27f113/src/main/java/hu/montlikadani/ragemode/events/EventListener.java#L97

**Comment by montlikadani** [comment]
> 
> 
> @montlikadani any idea why this is still happening? Im using the newest version. I think cancelling the right click event before teleporting would fix it completely. I mean adding:
> `event.setCancelled(true);`
> in this line would fix it:
> 
> https://github.com/montlikadani/RageMode/blob/3d6912f340f0c96b0b76b936bc5fd2c68b27f113/src/main/java/hu/montlikadani/ragemode/events/EventListener.java#L97

You can open a PR about this if you could test your implement and seeing if that works.

**Comment by AlexProgrammerDE** [comment]
nope. Still occurs... hm whats causing this?

**Comment by AlexProgrammerDE** [comment]
Ok you have two Interact event listeners. One transefers me and the other one instant executes my lobby item after joining. I think merging the event listeners would resolve this iisue.

**Comment by AlexProgrammerDE** [comment]
@montlikadani ok i finally fixed it! I delayed the world change event. I will open a PR now.
